# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70cf63de4c8188ca2faffe6d762e1a218695eb7b1e58a5161aa09d3f5d01da430b3eacc73b7a2b21e26f0a81d169c5eb301c3dc360d728370ab04e19cb6a9758

test:
  secret_key_base: 64a86ef9340309a97e7ba5b4f274f1577088810403630339a8eca9ab5052284d94b8ed1b1bf09c2624725b6ea5a7d0d146898bc13db6c550295a2ade32922f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
